# Generated by Django 4.2.4 on 2023-08-09 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0002_rename_show_theme_astronomyshow_show_themes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="planetariumdome",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="showtheme",
            options={"ordering": ["name"]},
        ),
    ]
