# Generated by Django 4.2.4 on 2023-08-09 23:16

from django.db import migrations, models
import planetarium.models


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0003_alter_planetariumdome_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="astronomyshow",
            name="image",
            field=models.ImageField(
                null=True, upload_to=planetarium.models.movie_image_file_path
            ),
        ),
    ]
